### PR TITLE
Glob pattern matching of URLs, and much, much more

### LINKED ISSUE #25: Use a glob matcher for URL matching
https://github.com/isaacs/minimatch

### LINKED ISSUE #30: If user inputs a url that already exists in the whitelist, no message is displayed.
In fact, nothing happens. The url will remain in the "url" textbox, even after you click "add to whitelist". This can possible confuse users. I suggest to add a red-text message similar to one that appears if the username or password is invalid.

### LINKED ISSUE #31: Import Whitelist from Local File

### LINKED ISSUE #32: Import Whitelist from Remote URL

### PR DESCRIPTION
**Pull request by Glavin001**
- [x] Blocked by #24.
- [x] Closes #25 
- [x] Closes #30 
- [x] Closes #31 
- [x] Closes #32 
  - Test URLs for remote URL whitelist:
    - [x] http://goo.gl/8gJsWo
    - [x] http://cs.smu.ca/~g_wiechert/CSCI3428/whitelist1.json

### CODE REVIEW

**Comment by Glavin001** [comment]
@nhernden would you like to take a look at this and test it and if you are comfortable, merge it into master. Thanks.

**Comment by ghost** [comment]
Checking now.

**Comment by Glavin001** [comment]
I am going to work on fixing this PR before we can merge it.

**Comment by Glavin001** [comment]
The following error is causing all websites to be allowed:

image

**Comment by Glavin001** [comment]
It is getting cluttered: 

image

Any ideas for improving the UI?

**Pull request merged**
